### ISSUE TITLE
Static call of non-static method PKPApplication::getRequest()

### ISSUE THREAD

**Issue by kirchnerf** [ulsdevteam/pkp-clamav#19]
On PHP 8.1 i get the following error when opening the settings form: 

`PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in /srv/www/htdocs/ojs-wup/plugins/generic/clamav/ClamavSettingsForm.inc.php:51`

Modifying the code by replacing `$request = Application::getRequest();` with `$request = Application::get()->getRequest();` seems to solve the problem.

**Comment by asmecher** [comment]
Cross-link: https://forum.pkp.sfu.ca/t/unable-to-configure-clamav-plugin-ojs-3-3-0-17/87107/2

**Comment by kirchnerf** [comment]
Fixed by #20
