### ISSUE TITLE
Plugin version working with OJS 2.4

### ISSUE THREAD

**Issue by johngrobler** [ulsdevteam/pkp-clamav#22]
I've attempted to install the plugin from the ojs-dev-2_4 branch on OJS 2.4.8.5 and it seems to install and configure successfully, however when I test it by uploading the EICAR test virus via new author submission, the file is not blocked and the virus is not detected. 

I've performed the same test with the plugin installed from the plugin gallery on OJS 3.3 and after configuring it with the same clamav path (/usr/bin/clamscan). It successfully detected the EICAR test virus via new author submission as expected.

Is there is working version of this plugin for OJS 2.4.x?

**Comment by ctgraham** [comment]
Hi, @johngrobler .  Be aware that PKP does not support OJS 2.4.x any longer and it is not maintained for with respect to any security or functional flaws.  Following PKP's maintenance cycle, the Pitt ULS only supports our plugins for currently supported releases of PKP software.

That said, I believe the plugin to have been functional as of the last supported OJS 2.4.8 release, via the `ojs-dev-2_4` branch.  My first sanity check would be try switching between the "socket" configuration and the "executable" configuration to test if one method works over the other.  (For example, selinux permissions may restrict socket or executable connections for some systems.)  The most effective configuration I have found is configuring `clamdscan` as the executable, with the benefit of using the daemon, but bypassing the complexity of the socket configuration.
