### ISSUE TITLE
Testing of plugin

### ISSUE THREAD

**Issue by woodyfon** [ulsdevteam/pkp-clamav#8]
Too bad there are no default values for daemon and socket.

It has been experimentally (in Debian/Ubuntu) established that for daemon is:
`/usr/sbin/clamd`
for socket:
`unix:///var/run/clamav/clamd.ctl`

**Comment by ctgraham** [comment]
Unfortunately the path to `clam` will vary with each operating system, distribution, and configuration.

Note that the first option in the configuration screen ("The system path to Clam AV's clamscan executable.") expects `clamscan` and not `clamd`.

If there are known common paths which we can include in the README, I'd be happy to merge a pull request.

**Comment by ctgraham** [comment]
I've added this example in the configuration notes:
https://github.com/ulsdevteam/pkp-clamav#configuration
